name: riverpod_graph
version: 0.0.1
homepage: https://riverpod.dev
repository: https://github.com/rrousselGit/riverpod

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  analyzer: ">=4.0.0 <4.1.0"
  collection: ^1.0.0
  path: ^1.8.2
